//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILS.UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_UserRole = new HashSet<tbl_UserRole>();
        }
    
        public string UserId { get; set; }
        public string Pno { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string FirstName { get; set; }
        public Nullable<decimal> IsDefault { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public string MiddleName { get; set; }
        public Nullable<decimal> IsDeleted { get; set; }
        public string Status { get; set; }
        public string UserType { get; set; }
        public string Organization { get; set; }
        public Nullable<System.DateTime> PasswordChangeDateTime { get; set; }
        public string PasswordStatus { get; set; }
    
        public virtual tbl_Unit tbl_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserRole> tbl_UserRole { get; set; }
    }
}
