//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILS.UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRole
    {
        public string RoleId { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> IsActive { get; set; }
        public Nullable<decimal> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<decimal> IsDefault { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
