//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILS.UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RolePermission
    {
        public string UpdatedBy { get; set; }
        public string RoleId { get; set; }
        public string PermissionId { get; set; }
        public Nullable<decimal> IsReadOnly { get; set; }
    
        public virtual tbl_Permission tbl_Permission { get; set; }
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
