//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAppDbContext : DbContext
    {
        public WebAppDbContext()
            : base("name=WebAppDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_ErrorLogs> tbl_ErrorLogs { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_MCAT> tbl_MCAT { get; set; }
        public virtual DbSet<tbl_Currency> tbl_Currency { get; set; }
        public virtual DbSet<C_Config_Master> C_Config_Master { get; set; }
        public virtual DbSet<tbl_Unit> tbl_Unit { get; set; }
        public virtual DbSet<tbl_Request> tbl_Request { get; set; }
        public virtual DbSet<M_PMS> M_PMS { get; set; }
        public virtual DbSet<tbl_RequestLog> tbl_RequestLog { get; set; }
        public virtual DbSet<M_MOP> M_MOP { get; set; }
        public virtual DbSet<M_MOP_ITEMS> M_MOP_ITEMS { get; set; }
        public virtual DbSet<tbl_PartType> tbl_PartType { get; set; }
        public virtual DbSet<tbl_Cage> tbl_Cage { get; set; }
        public virtual DbSet<tbl_Parts> tbl_Parts { get; set; }
        public virtual DbSet<C_Site_Config> C_Site_Config { get; set; }
        public virtual DbSet<tbl_ChildParts> tbl_ChildParts { get; set; }
        public virtual DbSet<V_MMS5> V_MMS5 { get; set; }
        public virtual DbSet<V_MSD> V_MSD { get; set; }
        public virtual DbSet<tbl_UnitType> tbl_UnitType { get; set; }
        public virtual DbSet<tbl_Mop_Images> tbl_Mop_Images { get; set; }
        public virtual DbSet<M_MOP_PLAN> M_MOP_PLAN { get; set; }
        public virtual DbSet<M_MOP_PLAN_HISTORY> M_MOP_PLAN_HISTORY { get; set; }
        public virtual DbSet<UserDashboardMapping> UserDashboardMappings { get; set; }
    }
}
