//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parts
    {
        public int PartId { get; set; }
        public string Part_No { get; set; }
        public Nullable<int> CageId { get; set; }
        public string CageCode { get; set; }
        public string PART_NAME { get; set; }
        public string NSN { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CurrencyID { get; set; }
        public string MCAT_ID { get; set; }
        public string PartTypeID { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public Nullable<int> PART_MEC { get; set; }
        public Nullable<decimal> MTBF { get; set; }
        public Nullable<decimal> MTTR { get; set; }
        public string SMR { get; set; }
        public Nullable<decimal> BRF { get; set; }
        public string PART_CHARACTERISTIC { get; set; }
        public string PICTURE_FILE_NAME { get; set; }
        public string File_Path { get; set; }
        public string FileExtension { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> ModifiedOnDate { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
        public string Status { get; set; }
        public string Model { get; set; }
    
        public virtual tbl_Cage tbl_Cage { get; set; }
        public virtual tbl_PartType tbl_PartType { get; set; }
        public virtual tbl_ChildParts tbl_ChildParts { get; set; }
    }
}
