//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RequestLog
    {
        public int RequestLogId { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string UserId { get; set; }
    }
}
