//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mop_Images
    {
        public int SiteId { get; set; }
        public string PmsNo { get; set; }
        public string MopNo { get; set; }
        public int ImageId { get; set; }
        public string ImageTitle { get; set; }
        public byte[] Image { get; set; }
        public string Remarks { get; set; }
    }
}
