//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Request
    {
        public int RequestId { get; set; }
        public string Part_No { get; set; }
        public string CageCode { get; set; }
        public string ManufacturerName { get; set; }
        public string Equipment_Name { get; set; }
        public string NSN { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public Nullable<int> PART_MEC { get; set; }
        public Nullable<decimal> MTBF { get; set; }
        public Nullable<decimal> MTTR { get; set; }
        public string SMR { get; set; }
        public Nullable<decimal> BRF { get; set; }
        public string PART_CHARACTERISTIC { get; set; }
        public string PICTURE_FILE_NAME { get; set; }
        public string File_Path { get; set; }
        public string FileExtension { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DateOfInstallation { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PMS_No { get; set; }
        public string SERIAL_NO { get; set; }
        public string JUSTIFICATION { get; set; }
        public string DETAIL_REMARKS { get; set; }
        public string LOCATIONS { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> CONTACT { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> ModifiedOnDate { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual tbl_Currency tbl_Currency { get; set; }
    }
}
