//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChildParts
    {
        public Nullable<int> ParentPartId { get; set; }
        public int ChildPartId { get; set; }
        public string APLNumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbl_Parts tbl_Parts { get; set; }
    }
}
