//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDashboardMapping
    {
        public string DashboardId { get; set; }
        public string IsDefault { get; set; }
        public string UserId { get; set; }
        public string IsPrefered { get; set; }
        public string RoleId { get; set; }
        public System.DateTime InsertionDateTime { get; set; }
        public string InsertedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public int Id { get; set; }
    }
}
