//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MMS5
    {
        public Nullable<int> Id { get; set; }
        public string Name { get; set; }
        public string PMS_No { get; set; }
        public string MOP_No { get; set; }
        public string Doc { get; set; }
        public string Jic { get; set; }
        public string By_Whom { get; set; }
        public Nullable<int> Periodicity { get; set; }
        public string Period { get; set; }
        public string Task_Procedure { get; set; }
        public string Safety_Precautions { get; set; }
        public Nullable<int> PartId { get; set; }
        public string Part_No { get; set; }
        public string PART_NAME { get; set; }
        public string Model { get; set; }
        public string MOP_Desc { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string AddReference { get; set; }
        public string PMS_ID { get; set; }
    }
}
