//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MSD
    {
        public string ID { get; set; }
        public string PMS_No { get; set; }
        public string MOP_No { get; set; }
        public int SiteId { get; set; }
        public int PartId { get; set; }
        public string Part_No { get; set; }
        public string NSN { get; set; }
        public string PART_NAME { get; set; }
        public Nullable<int> SR_Qty { get; set; }
        public Nullable<int> UR_Qty { get; set; }
        public string PMS_ID { get; set; }
        public string PartTypeID { get; set; }
    }
}
