//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SFD
    {
        public int SiteId { get; set; }
        public string Name { get; set; }
        public string ESWBS { get; set; }
        public string PESWBS { get; set; }
        public string Nomanclature { get; set; }
        public string Title { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PMS_No { get; set; }
        public string SMR_Code { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<int> CageId { get; set; }
        public string CageCode { get; set; }
        public string PART_NAME { get; set; }
        public string NSN { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CurrencyID { get; set; }
        public string Model { get; set; }
        public string CageName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}
