//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UNITS
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentUnitId { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public string UnitTypeName { get; set; }
        public Nullable<int> UnitTypeLevel { get; set; }
    }
}
